ENTPROG FINALS/Controllers/TransactionLogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using ENTPROG_FINALS.Data;
using ENTPROG_FINALS.Models;

using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace ENTPROG_FINALS.Controllers
{
    [Authorize]
    public class TransactionLogController : Controller 
    {
        private readonly ApplicationDbContext _context;

        public TransactionLogController(ApplicationDbContext context)
        {
            _context = context;
        }

        public User GetCurrentUser()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _context.Users.Where(u => u.Id == userId).SingleOrDefault();
            return user;
        }

        public IActionResult Index()
        {
            if (GetCurrentUser().RoleSetting != RoleType.Admin)
            {
                return RedirectToAction("Index", "Home");
            }

            var log = _context.Transactions.ToList();
            return View(log);
        }
    }
}

ENTPROG FINALS/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using ENTPROG_FINALS.Data;
using ENTPROG_FINALS.Models;

using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

using Microsoft.EntityFrameworkCore;



namespace ENTPROG_FINALS.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UserController(ApplicationDbContext context)
        {
            _context = context;
        }
        
        
        public User GetCurrentUser()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _context.Users.Where(u => u.Id == userId).SingleOrDefault();
            return user;
        }
        
        public IActionResult Index()
        {        
            if(GetCurrentUser().RoleSetting != RoleType.Admin)
            {
                return RedirectToAction("Index", "Home");
            }
            
            var users = _context.Users.ToList();
            return View(users);
        }

        public IActionResult Edit(Guid? id)
        {
            if (GetCurrentUser().RoleSetting != RoleType.Admin)
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var user = _context.Users.Where(i => i.Id == id.ToString()).SingleOrDefault();
            if (user == null)
            {
                return RedirectToAction("Index");
            }

            return View(user);
        }
        [HttpPost]
        public IActionResult Edit(Guid? id, User record)
        {
            var user = _context.Users.Where(i => i.Id == id.ToString()).SingleOrDefault();
            {
                user.FirstName = record.FirstName;
                user.LastName = record.LastName;
                user.Email = record.Email;
                user.UserName = record.Email;
            }
            _context.Users.Update(user);
            _context.SaveChanges();


            //Transaction Log
            var currentUser = GetCurrentUser();
            var transacLog = new Transaction();
            {
                transacLog.Table = "Members";
                transacLog.RecordID = user.Email;
                transacLog.Date = DateTime.Now;
                transacLog.User = currentUser.FirstName + currentUser.LastName;
                transacLog.TransactionMade = "UPDATE";
                transacLog.Anonymous = DonationType.Visible;
            }
            _context.Transactions.Add(transacLog);           
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Delete(Guid? id)
        {
            if (GetCurrentUser().RoleSetting != RoleType.Admin)
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var user = _context.Users.Where(i => i.Id == id.ToString()).SingleOrDefault();
            if (user == null)
            {
                return RedirectToAction("Index");
            }

            //Transaction Log
            var currentUser = GetCurrentUser();
            var transacLog = new Transaction();
            {
                transacLog.Table = "Members";
                transacLog.RecordID = user.Email;
                transacLog.Date = DateTime.Now;
                transacLog.User = currentUser.FirstName + currentUser.LastName;
                transacLog.TransactionMade = "DELETE";
                transacLog.Anonymous = DonationType.Visible;
            }
            _context.Transactions.Add(transacLog);
            _context.SaveChanges();

            _context.Users.Remove(user);
            _context.SaveChanges();

            return RedirectToAction();
        }

    }
}

ENTPROG FINALS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ENTRPOG_FINALS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/dataTables.bootstrap4.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color: #CEF6F5;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Back up to the Front</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Donations" asp-action="List">Donations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Beneficiary" asp-action="Index">Beneficiaries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TransactionLog" asp-action="Index">Transactions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>


                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ENTPROG_FINALS - <a asp-area="" asp-controller="Home" asp-action="Privacy">About Us</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>